const mongoose=require('mongoose')
const productSchema=mongoose.Schema({
    name:{
        type:String,
        require:true,
        unique:true,
    },
    desc:{
        type:String,
        require:true,
        unique:true,
    },
    productImage:{
        type:String
    },
    price:{
        type:Number,
        default:0
    },
    stock:{
        type:Number,
        default:0
    },
    category:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Category",
        require:true
    },
    owner:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User"
    }
},
{timestamps:true}
)
module.exports=mongoose.model('Product',productSchema);