const express= require('express');
const { RESISTRATION, LOGIN, updateUser,changePassword, sendUserPasswordResetEmail,resetPassword, sendNotification, logout} = require('../controllers/user.controller');
const auth = require('../middlewares/user.auth');
const multer = require('../middlewares/user.multer');
const route=express.Router();
route.post('/resis',multer,RESISTRATION);
route.post('/login',LOGIN);
route.put('/update',auth,multer,updateUser);
route.post('/change',auth,changePassword);
route.post('/send',sendUserPasswordResetEmail);
route.post('/reset/:id/:token',resetPassword);
route.post('/send-notification',auth,sendNotification);
route.get('/logout',auth,logout);
module.exports=route;